In [1]:
import numpy as np
from numpy import matrix, zeros, size
from numpy.linalg import det

In [2]:
n = int(input('Ingrese el tamaño de su matriz cuadrada: '))

A = np.array([])

Ag = []

print('Ingrese los valores de la matriz cuadrada')

for i in range(0,n**2):
    x = float(input('Ingrese elementos: '))
    A = np.append(A,x)
    Ag.append(x)

A = A.reshape(n,n)

A
        

Ingrese el tamaño de su matriz cuadrada:  3


Ingrese los valores de la matriz cuadrada


Ingrese elementos:  1
Ingrese elementos:  4
Ingrese elementos:  2
Ingrese elementos:  2
Ingrese elementos:  4
Ingrese elementos:  4
Ingrese elementos:  4
Ingrese elementos:  2
Ingrese elementos:  3


array([[1., 4., 2.],
       [2., 4., 4.],
       [4., 2., 3.]])

In [3]:
B = np.array([])

Bg = []

print('Ingrese los valores de la matriz constante')

for i in range (0,n):
    y = float(input('Ingrese elementos: '))
    B = np.append(B,y)
    Bg.append(y)

B = B.reshape(n,1)
B

Ingrese los valores de la matriz constante


Ingrese elementos:  72
Ingrese elementos:  104
Ingrese elementos:  88


array([[ 72.],
       [104.],
       [ 88.]])

In [4]:
Inv = np.linalg.inv(A)
Inv

array([[ 2.00000000e-01, -4.00000000e-01,  4.00000000e-01],
       [ 5.00000000e-01, -2.50000000e-01, -5.94762335e-18],
       [-6.00000000e-01,  7.00000000e-01, -2.00000000e-01]])

In [5]:
C = np.dot(Inv,B)
C

array([[ 8.],
       [10.],
       [12.]])

In [6]:
print('El valor de x es: ', C[0])
print('El valor de y es: ', C[1])
print('El valor de z es: ', C[2])

El valor de x es:  [8.]
El valor de y es:  [10.]
El valor de z es:  [12.]


In [7]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm
%matplotlib auto

Using matplotlib backend: Qt5Agg


In [8]:
x1,y1 = np.linspace(-20,20,100), np.linspace(-20,20,100)
X,Y = np.meshgrid(x1,y1)

In [9]:
Z1 = (Bg[0]-Ag[0]*X-Ag[1])/Ag[2]
Z2 = (Bg[1]-Ag[3]*X-Ag[4])/Ag[5]
Z3 = (Bg[2]-Ag[6]*X-Ag[7])/Ag[8]

In [10]:
fig = plt.figure()

ax = fig.add_subplot(111, projection = '3d')

ax.plot_surface(X,Y,Z1, alpha = 0.8, cmap = cm.Accent, rstride = 100, cstride = 100)
ax.plot_surface(X,Y,Z2, alpha = 0.8, cmap = cm.Paired, rstride = 100, cstride = 100)
ax.plot_surface(X,Y,Z3, alpha = 0.8, cmap = cm.hot, rstride = 100, cstride = 100)

ax.set_xlabel('Eje x')
ax.set_ylabel('Eje y')
ax.set_zlabel('Eje z')

Text(0.5, 0, 'Eje z')

### 